---
_extends: .github

repository:
  name: go-toxcore-c
  description: The golang bindings for libtoxcore (Project Tox).
  topics: toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy Static Code Analysis
          - code-review/reviewable
